# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1595a1be9022f24fe5366421e22f12a7291a15b55a5cb082bca662015e959f838034cf92cd188e314e44731062a8abf0621bf6437268ebf3fa69422e7e56ea2

test:
  secret_key_base: 3f42a64a813919828a62fc5ce0e79f285e525da18bd3290656c11dadd93dd3b4a53418b408837d9efe116b8d68bd7cce2b1c452e0feb0f0652d50c339e16b9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
